### ISSUE TITLE
Macro call results in parse error

### ISSUE THREAD

**Issue by rdeits** [jamesdanged/Jude#4]
I'm getting parse errors on files that include macro calls. For example:

```julia
using BinDeps

@BinDeps.setup
```

fails with:

```
/Users/rdeits/.julia/v0.4/LCMGL/deps/build.jl Error: Unexpected symbol
    at InvalidParseError (/Users/rdeits/.atom/packages/Jude/dist/utils/errors.js:18:14)
    at throwParseErrorFailedToFindArc (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:120:15)
    at runFsaHelper (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:89:13)
    at Object.runFsaStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:55:5)
    at MacroCallFsa.runStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/bracketed/MacroCallFsa.js:76:20)
    at Object.parseMacroCall (/Users/rdeits/.atom/packages/Jude/dist/fsas/bracketed/MacroCallFsa.js:128:18)
    at Arc.readMacroInvocation [as onSuccessParseStreamCallback] (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ExpressionFsa.js:569:31)
    at runFsaHelper (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:83:22)
    at Object.runFsaStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:55:5)
    at ExpressionFsa.runStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ExpressionFsa.js:302:20)
    at Object.parseGeneralBlockExpression (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ExpressionFsa.js:620:38)
    at Arc.readBodyExpression [as onSuccessParseStreamCallback] (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ModuleContentsFsa.js:281:32)
    at runFsaHelper (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:83:22)
    at Object.runFsaStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/fsaUtils.js:55:5)
    at ModuleContentsFsa.runStartToStop (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ModuleContentsFsa.js:192:20)
    at Object.parseWholeFileContents (/Users/rdeits/.atom/packages/Jude/dist/fsas/general/ModuleContentsFsa.js:401:27)
    at Object.parseFile (/Users/rdeits/.atom/packages/Jude/dist/parseTree/parseFile.js:55:51)
    at /Users/rdeits/.atom/packages/Jude/dist/core/parseWorkspace.js:41:33
    at /Users/rdeits/.atom/packages/Jude/dist/utils/taskUtils.js:20:27(anonymous function) @ parseWorkspace.ts:50step @ parseWorkspace.ts:1onfulfill @ parseWorkspace.ts:1
parseWorkspace.ts:50 /Users/rdeits/.julia/v0.4/LCMGL/src/LCMGL.jl Error: Unexpected symbol(…)(anonymous function) @ parseWorkspace.ts:50step @ parseWorkspace.ts:1onfulfill @ parseWorkspace.ts:1
```

**Comment by jamesdanged** [comment]
Thanks, I'll look into fixing that up. I only had it handling syntax like `BinDeps.@setup`

**Comment by jamesdanged** [comment]
The latest release should fix this.
